# Generated by Django 5.0.4 on 2024-04-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phoneNo', models.CharField(blank=True, max_length=20)),
                ('addressDetails', models.JSONField(default=dict)),
                ('workExperience', models.JSONField(default=list)),
                ('qualifications', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('photo', models.TextField(blank=True)),
            ],
        ),
    ]
